create table public.groups (
  id smallint generated by default as identity not null,
  name text not null,
  days_of_week smallint[] not null default '{}'::smallint[],
  constraint groups_pkey primary key (id),
  constraint groups_name_key unique (name)
) TABLESPACE pg_default;
