@startuml attendances
(E)
:response 400 error;
stop

start
if (user valid?) then (no)
  (E)
  detach
else (yes)
endif
if (can set attendance?) then (no)
  if (action) then (set)
    (E)
    detach
  else (verify)
    :response 200 false;
  endif
else (yes)
  if (action) then (set)
    if (attendance setted?) then (no)
      (E)
      detach
    else (yes)
    endif
  else (verify)
  endif
  :response 200 true;
endif
stop
@enduml
