@startuml attendances
(E)
:response not 200 status;
stop

start
if (payload valid?) then (no)
  (E)
  detach
else (yes)
endif
if (user valid?) then (no)
  (E)
  detach
else (yes)
endif
if (can set attendance?) then (no)
  (E)
  detach
else (yes)
endif
if (action) then (verify)
  :response 200 status;
else if (action) then (set)
  if (attendance setted?) then (yes)
    :response 200 status;
  else (no)
    :response 500 status;
  endif
else
  :I'm a teapot;
endif
stop
@enduml
